version: "2.1"
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./database:/data
    ports:
      - "27017:27017"
  app:
    container_name: starlink
    image: wimali2/starlinkrepo:latest
    ports:
      - 8083:8081
    depends_on:
      - mongo
