apiVersion: apps/v1
kind: Deployment
metadata:
  name: starlink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starlink
  template:
    metadata:
      labels:
        app: starlink
    spec:
      containers:
        - name: app
          image: wimali2/starlinkrepo
          ports:
            - containerPort: 8081
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: starlink
spec:
  selector:
    app: starlink
  ports:
    - port: 80
      targetPort: 8081
  type: LoadBalancer